const serviceData = [
  {
    id: "general",
    category: "General Dentistry",
    name: "General Dentistry",
    price: 500,
    iconSlug: "root-canal",
    svgSrc: "/images/services/General Dentistry.svg",
    tagline: "Regular check-ups and professional cleanings to maintain your oral health.",
    steps: [
      { title: "Examination", desc: "Full clinical exam of teeth, gums, and bite." },
      { title: "Digital X-rays", desc: "Low-radiation X-rays to spot hidden issues early." },
      { title: "Professional Cleaning", desc: "Plaque and tartar removed above and below the gumline." },
      { title: "Treatment Plan", desc: "Personalised plan created for any issues found." },
      { title: "Preventive Advice", desc: "Brushing, flossing, and diet tips for lasting health." },
    ],
    what: "General dentistry covers everything needed to keep your mouth healthy — routine check-ups, professional cleanings, fillings, and early detection of issues like cavities and gum disease. Regular visits every 6 months prevent small problems from becoming costly ones.",
    why: ["Digital X-rays with 80% less radiation", "Comprehensive exam in a single visit", "Painless fillings with composite resin", "Preventive care tailored to your needs"],
    before: null,
    after: null,
    faqs: [
      { question: "How often should I visit the dentist?", answer: "Every 6 months for a healthy adult. Children and those with gum disease may need visits every 3–4 months." },
      { question: "Does a cleaning hurt?", answer: "Professional cleaning is generally painless. Mild sensitivity is normal for a few hours afterward." },
      { question: "What does a check-up include?", answer: "Examination of all teeth, gums, tongue, and jaw; digital X-rays; and a professional cleaning — all in one visit." },
    ],
  },
  {
    id: "orthodontics",
    category: "Orthodontics",
    name: "Orthodontics",
    price: 18000,
    iconSlug: "braces",
    svgSrc: "/images/services/Orthodontics.svg",
    tagline: "Straighten your teeth and align your bite — your way.",
    steps: [
      { title: "Consultation", desc: "Teeth and bite assessed; treatment options presented." },
      { title: "Digital Moulds & X-rays", desc: "Precise records taken for treatment planning." },
      { title: "Fitting", desc: "Braces or clear aligners fitted in a single appointment." },
      { title: "Monthly Adjustments", desc: "Regular visits to track progress and make adjustments." },
      { title: "Retainer", desc: "Retainer fitted on completion to maintain alignment." },
    ],
    what: "Orthodontics corrects crooked teeth, gaps, crowding, and bite problems using braces or clear aligners. We offer traditional metal braces, ceramic braces, and Invisalign — all designed to give you a straight, confident smile.",
    why: ["Free initial orthodontic consultation", "Invisalign-certified provider", "Ceramic and lingual options available", "Retainer included in all packages"],
    before: null,
    after: null,
    faqs: [
      { question: "How long does orthodontic treatment take?", answer: "Typically 12–24 months. Simple cases with clear aligners can be as short as 6 months." },
      { question: "Are clear aligners as effective as braces?", answer: "For mild to moderate cases, yes. Severe crowding may require traditional braces." },
      { question: "Do braces hurt?", answer: "Mild soreness for 2–3 days after fitting and adjustments is normal and manageable." },
    ],
  },
  {
    id: "cosmetic",
    category: "Cosmetic Dentistry",
    name: "Cosmetic Dentistry",
    price: 3500,
    iconSlug: "smile",
    svgSrc: "/images/services/Cosmetic Dentistry.svg",
    tagline: "Enhance your smile with treatments tailored to boost your confidence.",
    steps: [
      { title: "Smile Analysis", desc: "We assess your teeth, gums, lips, and face for a complete picture." },
      { title: "Digital Smile Preview", desc: "See your new smile on screen before any treatment begins." },
      { title: "Treatment Selection", desc: "Whitening, veneers, bonding, or contouring — chosen for your goals." },
      { title: "Procedure", desc: "Treatment carried out with precision and care." },
      { title: "Final Review", desc: "Results checked and aftercare guidance provided." },
    ],
    what: "Cosmetic dentistry focuses on improving the appearance of your smile through teeth whitening, porcelain veneers, composite bonding, gum contouring, and smile designing. We use digital smile design to preview your results before treatment begins.",
    why: ["Digital smile preview before treatment", "Ultra-thin porcelain veneers", "Minimally invasive techniques", "Natural-looking, long-lasting results"],
    before: null,
    after: null,
    faqs: [
      { question: "How many sessions does a smile makeover take?", answer: "Typically 3–5 visits over 2–4 weeks depending on the procedures selected." },
      { question: "Are veneers permanent?", answer: "Veneers last 10–15 years. They require minimal tooth reduction which is irreversible." },
      { question: "How much does cosmetic dentistry cost?", answer: "Costs vary by procedure. We provide a detailed cost estimate after your smile analysis consultation." },
    ],
  },
  {
    id: "root-canal",
    category: "General Dentistry",
    name: "Root Canal Treatment",
    price: 3999,
    iconSlug: "root-canal",
    tagline: "Save your tooth. End the pain. Single visit.",
    steps: [
      { title: "Diagnosis & X-ray", desc: "Digital X-ray and clinical exam to assess infection depth." },
      { title: "Anaesthesia", desc: "Local anaesthesia administered — you feel nothing." },
      { title: "Pulp Removal", desc: "Infected pulp removed with rotary instruments." },
      { title: "Canal Cleaning", desc: "Canals shaped, irrigated, and disinfected precisely." },
      { title: "Sealing & Crown", desc: "Tooth sealed and a permanent crown placed." },
    ],
    what: "Root canal treatment (endodontic therapy) removes the infected pulp from inside a tooth, cleans the canal, and seals it — saving the tooth from extraction. With modern rotary instruments, the procedure is single-visit and completely painless.",
    why: ["Single-visit with rotary endodontics", "Digital apex locator for precision", "5-year warranty on treated tooth", "0% EMI on all amounts"],
    before: null,
    after: null,
    faqs: [
      { question: "Is root canal painful?", answer: "No. Local anaesthesia ensures you feel nothing. Post-procedure soreness resolves within 48 hours." },
      { question: "How many visits does it take?", answer: "Most cases are completed in a single 60–90 minute visit using rotary instruments." },
      { question: "Can I eat after a root canal?", answer: "Avoid chewing on that side until the permanent crown is placed, usually within 1–2 weeks." },
    ],
  },
  {
    id: "implants",
    category: "General Dentistry",
    name: "Dental Implants",
    price: 25000,
    iconSlug: "implants",
    svgSrc: "/images/services/Dental Implants.svg",
    tagline: "Permanent teeth. Natural feel. Lifetime confidence.",
    steps: [
      { title: "Consultation & 3D Scan", desc: "CBCT scan assesses bone density and implant position." },
      { title: "Implant Placement", desc: "Titanium post surgically placed in the jawbone." },
      { title: "Osseointegration", desc: "3–6 months for implant to fuse with the bone." },
      { title: "Crown Fitting", desc: "Custom porcelain crown attached for a natural look." },
    ],
    what: "Dental implants are titanium posts surgically placed in the jawbone to replace missing tooth roots. A crown is attached on top, resulting in a permanent, natural-looking tooth replacement with no slipping or discomfort.",
    why: ["Swiss-made titanium implants", "Lifetime warranty on implant body", "Same-day crown option available", "Bone graft if required"],
    before: null,
    after: null,
    faqs: [
      { question: "How long do implants last?", answer: "With proper care, implants can last a lifetime. The crown typically lasts 10–15 years." },
      { question: "Am I a candidate for implants?", answer: "Most adults with good bone density qualify. We assess via 3D CBCT scan during consultation." },
      { question: "Is the surgery painful?", answer: "The procedure is done under local anaesthesia. Most patients report less discomfort than a tooth extraction." },
    ],
  },
  {
    id: "whitening",
    category: "Cosmetic Dentistry",
    name: "Teeth Whitening",
    price: 3500,
    iconSlug: "whitening",
    tagline: "8 shades brighter. 45 minutes. Zero sensitivity.",
    steps: [
      { title: "Shade Assessment", desc: "Current tooth shade recorded for comparison." },
      { title: "Gel Application", desc: "Medical-grade bleaching gel applied to teeth." },
      { title: "LED Activation", desc: "LED light activates gel — 45 minutes, pain-free." },
      { title: "Take-home Kit", desc: "Custom tray provided to maintain results at home." },
    ],
    what: "Professional in-office laser whitening uses medical-grade bleaching gel activated by LED light to break down stains and discolouration. Results are visible immediately — up to 8 shades brighter in a single 45-minute session.",
    why: ["Up to 8 shades brighter in 45 mins", "Safe for enamel (pH-neutral gel)", "Take-home kit included", "Long-lasting up to 12 months"],
    before: null,
    after: null,
    faqs: [
      { question: "Does whitening cause sensitivity?", answer: "Mild sensitivity lasting 24–48 hours is normal. We use desensitising gel to minimise this." },
      { question: "How long do results last?", answer: "6–12 months depending on diet and habits. Touch-up trays extend results significantly." },
      { question: "Can I whiten with veneers or crowns?", answer: "Whitening only works on natural tooth enamel. We advise whitening before placing veneers/crowns." },
    ],
  },
  {
    id: "braces",
    category: "Cosmetic Dentistry",
    name: "Braces & Aligners",
    price: 18000,
    iconSlug: "braces",
    tagline: "Straight teeth. Your way. Metal, ceramic, or invisible.",
    steps: [
      { title: "Consultation", desc: "Teeth and bite assessed; treatment plan prepared." },
      { title: "X-rays & Moulds", desc: "Digital moulds and OPG taken for precision planning." },
      { title: "Fitting", desc: "Braces or aligners fitted in a single appointment." },
      { title: "Monthly Adjustments", desc: "Regular visits to monitor progress and adjust." },
      { title: "Retainer", desc: "Retainer fitted on completion to hold alignment." },
    ],
    what: "We offer metal braces, ceramic braces, and clear aligners (Invisalign) to correct crooked teeth, gaps, and bite problems. Treatment is customised to your lifestyle — whether you prefer discreet or affordable options.",
    why: ["Free initial consultation", "Invisalign certified provider", "Ceramic/lingual options available", "Retainer included in package"],
    before: null,
    after: null,
    faqs: [
      { question: "How long does orthodontic treatment take?", answer: "Typically 12–24 months depending on complexity. Minor cases with aligners can be 6–12 months." },
      { question: "Are clear aligners as effective as braces?", answer: "For mild to moderate cases, yes. Severe crowding or bite issues may require traditional braces." },
      { question: "Do braces hurt?", answer: "Initial soreness for 2–3 days after fitting and adjustments is normal and manageable with OTC pain relief." },
    ],
  },
  {
    id: "smile",
    category: "Cosmetic Dentistry",
    name: "Smile Designing",
    price: 8000,
    iconSlug: "smile",
    tagline: "Preview your perfect smile before we begin.",
    steps: [
      { title: "Digital Smile Preview", desc: "See your new smile on screen before treatment starts." },
      { title: "Treatment Planning", desc: "Procedures selected — whitening, veneers, contouring." },
      { title: "Preparation", desc: "Teeth gently prepared; temporary veneers placed." },
      { title: "Veneers / Bonding", desc: "Custom porcelain veneers or composite bonding applied." },
      { title: "Final Polish", desc: "Bite checked, final polish, and aftercare guidance." },
    ],
    what: "Smile designing is a comprehensive cosmetic procedure combining teeth whitening, veneers, bonding, gum contouring, and other treatments to create your ideal smile. We use digital smile design software to preview results before treatment begins.",
    why: ["Digital smile preview before treatment", "Custom ultra-thin porcelain veneers", "Minimally invasive techniques", "Natural-looking, long-lasting results"],
    before: null,
    after: null,
    faqs: [
      { question: "How many appointments does a smile makeover take?", answer: "Typically 3–5 visits over 2–4 weeks depending on the procedures involved." },
      { question: "Are veneers permanent?", answer: "Veneers last 10–15 years. They require minimal tooth reduction which is irreversible." },
      { question: "How much does a full smile makeover cost?", answer: "Costs vary by number of teeth and procedures. We offer a detailed cost breakdown after the digital consultation." },
    ],
  },
  {
    id: "kids",
    category: "Kids Dentistry",
    name: "Kids Dentistry",
    price: 800,
    iconSlug: "kids",
    svgSrc: "/images/services/Pediatric Dentistry.svg",
    tagline: "Gentle, fun, and completely stress-free for your child.",
    steps: [
      { title: "Fun Introduction", desc: "Child meets the team and gets comfortable with the chair." },
      { title: "Gentle Check-up", desc: "Teeth and gums examined in a stress-free way." },
      { title: "Cleaning & Fluoride", desc: "Professional cleaning and fluoride application." },
      { title: "Sealants", desc: "Pit and fissure sealants applied to prevent cavities." },
      { title: "Parent Guidance", desc: "Brushing tips and diet advice shared with parents." },
    ],
    what: "Our child-friendly dental clinic is designed to make every visit fun and stress-free. We specialise in preventive care, pit and fissure sealants, fluoride treatments, and space maintainers for growing smiles.",
    why: ["Child-friendly environment & TV screens", "Behaviour management & nitrous oxide", "Fluoride & sealant programmes", "Parents welcome in treatment room"],
    before: null,
    after: null,
    faqs: [
      { question: "When should my child first see a dentist?", answer: "By age 1 or within 6 months of the first tooth erupting — whichever comes first." },
      { question: "Are dental X-rays safe for children?", answer: "Yes. Digital X-rays use 80–90% less radiation than traditional X-rays and are completely safe." },
      { question: "What is a space maintainer?", answer: "If a baby tooth is lost early, a space maintainer holds the gap open for the permanent tooth to erupt correctly." },
    ],
  },
  {
    id: "wisdom",
    category: "General Dentistry",
    name: "Wisdom Tooth Extraction",
    price: 2500,
    iconSlug: "wisdom",
    tagline: "Safe, painless removal with faster healing.",
    steps: [
      { title: "OPG X-ray", desc: "Panoramic X-ray to assess root position and angulation." },
      { title: "Anaesthesia", desc: "Local anaesthesia ensures a completely pain-free procedure." },
      { title: "Extraction", desc: "Surgical or simple extraction performed in 20–40 mins." },
      { title: "PRF Placement", desc: "Platelet-rich fibrin placed for faster, better healing." },
      { title: "Aftercare Kit", desc: "Medicines, instructions, and follow-up appointment provided." },
    ],
    what: "Wisdom teeth (third molars) often cause pain, infection, or misalignment when they don't have enough room to erupt. Our oral surgeons perform surgical and simple extractions under local anaesthesia with minimal recovery time.",
    why: ["OPG X-ray analysis before extraction", "Surgical & simple extraction", "Platelet-rich fibrin (PRF) for faster healing", "Post-operative care kit included"],
    before: null,
    after: null,
    faqs: [
      { question: "Do all wisdom teeth need to be removed?", answer: "No. Only those that are impacted, causing pain, decay, or shifting adjacent teeth require extraction." },
      { question: "How long is recovery?", answer: "Soft tissue heals in 7–10 days. Bone heals fully over 3–6 months. Most patients return to work in 2–3 days." },
      { question: "Can I eat after extraction?", answer: "Stick to soft foods (curd, idli, dal) for 5–7 days. Avoid hot, spicy, and crunchy foods." },
    ],
  },
  {
    id: "gum",
    category: "General Dentistry",
    name: "Gum Treatment",
    price: 1500,
    iconSlug: "gum",
    tagline: "Healthy gums. Stronger teeth. Lasting results.",
    steps: [
      { title: "Assessment & Probing", desc: "Pocket depth measured to grade disease severity." },
      { title: "Scaling", desc: "Ultrasonic scaler removes plaque and tartar above gumline." },
      { title: "Root Planing", desc: "Root surfaces smoothed to prevent bacteria re-attachment." },
      { title: "Laser Therapy", desc: "Laser targets remaining bacteria deep in pockets." },
      { title: "Review & Maintenance", desc: "Follow-up to confirm healing; maintenance schedule set." },
    ],
    what: "Gum disease (periodontitis) is the leading cause of tooth loss in adults. Our periodontal treatments include scaling, root planing, laser gum therapy, and flap surgery to restore gum health and prevent bone loss.",
    why: ["Laser-assisted gum therapy", "Ultrasonic scaling for deep cleaning", "Bleeding gums addressed in 1 visit", "Maintenance programme included"],
    before: null,
    after: null,
    faqs: [
      { question: "Is bleeding gum a serious problem?", answer: "Yes. Bleeding gums indicate gingivitis or early periodontitis. Left untreated, it progresses to bone loss and tooth loss." },
      { question: "How many gum treatment sessions are needed?", answer: "Mild-moderate cases need 2–4 sessions. Advanced cases may require surgical intervention." },
      { question: "Can gum disease be cured?", answer: "Gingivitis is fully reversible. Advanced periodontitis can be controlled but requires ongoing maintenance." },
    ],
  },
  {
    id: "emergency",
    category: "Emergency Care",
    name: "Emergency Dental Care",
    price: 500,
    iconSlug: "emergency",
    svgSrc: "/images/services/Emergency Care.svg",
    tagline: "Same-day appointments. Pain relief in 30 minutes.",
    steps: [
      { title: "Call / WhatsApp", desc: "Contact us — we triage your case immediately." },
      { title: "Same-day Slot", desc: "Emergency appointment confirmed within the hour." },
      { title: "Pain Relief", desc: "Immediate pain relief within 30 minutes of arrival." },
      { title: "Treatment", desc: "Root cause diagnosed and treated in the same visit." },
      { title: "Follow-up", desc: "Follow-up scheduled to ensure complete recovery." },
    ],
    what: "Dental emergencies — toothaches, broken teeth, knocked-out teeth, lost fillings — require immediate attention. We offer same-day emergency appointments and are available on WhatsApp for triage advice 24/7.",
    why: ["Same-day emergency appointments", "WhatsApp triage available 24/7", "Pain relief within 30 minutes of arrival", "Sunday & holiday availability"],
    before: null,
    after: null,
    faqs: [
      { question: "What counts as a dental emergency?", answer: "Severe toothache, knocked-out tooth, broken tooth with sharp edges, lost crown/filling, or facial swelling." },
      { question: "What should I do with a knocked-out tooth?", answer: "Keep it moist (in milk or saliva), don't clean it, and reach us within 30–60 minutes for the best chance of re-implantation." },
      { question: "Do you charge extra for emergency visits?", answer: "A nominal emergency consultation fee applies. We waive this if you proceed with treatment on the same day." },
    ],
  },
];

export default serviceData;
